default:
  image: ruby:3.1.1

before_script:
  - gem install bundler -N
  - bundle install --jobs $(nproc) "${FLAGS[@]}"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - export CC_TEST_REPORTER_ID=6b1cc8aaef71de13ce30c6cdb0d9b4e789ae0ea9949f47d211f5b6107f45d4ff

test:
  script:
    - ./cc-test-reporter before-build
    - bundle exec rake
    - ./cc-test-reporter after-build
